Algoritmo "consumo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Igo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Alana
// Data atual  : 30/05/2025
Var
distancia, combustivel, consumo: real

Inicio
escreva("Distância percorrida (km): ")
leia(distancia)
escreva("Combustível gasto (litros): ")
leia(combustivel)

Fimalgoritmo